import Head from "next/head";
import styles from "../styles/Home.module.css";

import Layout from "../components/layout/Layout";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    if (localStorage.getItem("theme")) {
      document.documentElement.dataset.theme = localStorage.getItem("theme");
    }
  }, []);

  return (
    <div className={styles.container} data-theme="dark">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Layout />
      </main>
    </div>
  );
}
